name: Test

on: 
  push:

jobs:
  lint:
    env:
      GH_TOKEN: ${{secrets.GH_TOKEN}}
    runs-on: ubuntu-latest
    name: Test ${{matrix.zig}}
    strategy:
      matrix:
        zig:
          - "beta"
          - "edge"
    steps:
      - uses: actions/checkout@v2

      - name: Setup Zig
        run: sudo snap install zig --classic --${{matrix.zig}}

      - run: zig version
      - run: zig test **/*_test.zig
