name: Test

on: 
  push:
    branches:
      - master
      - "[0-9]+-[0-9]+-stable"
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 2 * * 0"

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test ${{matrix.zig}}
    strategy:
      fail-fast: false
      matrix:
        zig:
          - "beta"
          - "edge"
    steps:
      - uses: actions/checkout@v2

      - name: Setup Zig
        run: sudo snap install zig --classic --${{matrix.zig}}

      - run: zig version
      - run: zig test **/*_test.zig
